### 陣列的運算

- 如何快速創立隨機陣列/矩陣
- 陣列運算
- 矩陣運算

In [4]:
import numpy as np

# 0-9之間隨機產生，長度為10的1D array
np.random.randn(10)

array([ 0.3108199 , -0.29966212,  0.50323289,  1.73599896,  0.63097178,
        2.48128153,  0.02596414, -0.62166347,  0.61705411, -0.34497662])

In [10]:
# 0-9之間整數隨機產生，size 2x3的矩陣
np.random.randint(10, size=(2, 3))

array([[0, 3, 5],
       [3, 2, 5]])

In [11]:
# 使用.reshape方法重塑矩陣，指定想要的樣子

np.random.randint(10, size=20).reshape(4, 5)

array([[2, 1, 5, 4, 4],
       [1, 6, 6, 4, 3],
       [9, 6, 7, 8, 3],
       [0, 1, 9, 4, 4]])

### 陣列運算

In [12]:
a = np.random.randint(10, size=20).reshape(4, 5)
b = np.random.randint(10, size=20).reshape(4, 5)

In [13]:
a

array([[1, 5, 8, 5, 5],
       [9, 8, 0, 3, 5],
       [0, 9, 8, 7, 9],
       [5, 9, 0, 9, 1]])

In [14]:
b

array([[8, 2, 9, 0, 2],
       [1, 7, 6, 6, 1],
       [4, 9, 2, 8, 5],
       [8, 6, 6, 9, 8]])

In [15]:
# 陣列相加
a + b

array([[ 9,  7, 17,  5,  7],
       [10, 15,  6,  9,  6],
       [ 4, 18, 10, 15, 14],
       [13, 15,  6, 18,  9]])

In [16]:
a - b

array([[-7,  3, -1,  5,  3],
       [ 8,  1, -6, -3,  4],
       [-4,  0,  6, -1,  4],
       [-3,  3, -6,  0, -7]])

In [17]:
# 陣列乘法
a * b

array([[ 8, 10, 72,  0, 10],
       [ 9, 56,  0, 18,  5],
       [ 0, 81, 16, 56, 45],
       [40, 54,  0, 81,  8]])

In [19]:
# 陣列除法
# 由於隨機數中有零，除數為0的狀況會使拋出RuntimeWarning: divide by zero encountered in true_divide
a / b

/anaconda3/envs/python37/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([[0.125     , 2.5       , 0.88888889,        inf, 2.5       ],
       [9.        , 1.14285714, 0.        , 0.5       , 5.        ],
       [0.        , 1.        , 4.        , 0.875     , 1.8       ],
       [0.625     , 1.5       , 0.        , 1.        , 0.125     ]])

### 矩陣的運算
- 前述創立陣列的方法都可轉換成矩陣
- 定義更改後計算意義也不同

In [20]:
# 利用 陣列ndarray轉矩陣matrix

np.mat(a)

matrix([[1, 5, 8, 5, 5],
        [9, 8, 0, 3, 5],
        [0, 9, 8, 7, 9],
        [5, 9, 0, 9, 1]])

In [21]:
A = np.mat(a)
B = np.mat(b)

In [23]:
# 矩陣加法
A + B

matrix([[ 9,  7, 17,  5,  7],
        [10, 15,  6,  9,  6],
        [ 4, 18, 10, 15, 14],
        [13, 15,  6, 18,  9]])

In [24]:
# 矩陣減法
A - B

matrix([[-7,  3, -1,  5,  3],
        [ 8,  1, -6, -3,  4],
        [-4,  0,  6, -1,  4],
        [-3,  3, -6,  0, -7]])

In [25]:
# 直接相乘會出錯，因為矩陣乘法 A 行數 要等於B列數
A * B

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [30]:
# 利用陣列轉矩陣，隨機產生
a = np.mat(np.random.randint(10, size=20).reshape(4, 5))
b = np.mat(np.random.randint(10, size=20).reshape(5, 4))

In [31]:
a

matrix([[9, 0, 2, 0, 2],
        [0, 1, 3, 0, 0],
        [3, 6, 4, 6, 5],
        [4, 0, 7, 9, 9]])

In [32]:
b

matrix([[1, 5, 9, 0],
        [2, 1, 3, 3],
        [5, 0, 1, 0],
        [8, 7, 7, 4],
        [5, 3, 8, 4]])

In [33]:
# matrix size 合運算邏輯，可相乘
a * b

matrix([[ 29,  51,  99,   8],
        [ 17,   1,   6,   3],
        [108,  78, 131,  62],
        [156, 110, 178,  72]])

### Array常用函數

In [36]:
# 0-9整數值間隨機產生 4x5陣列
a = np.random.randint(10, size=20).reshape(4, 5)

In [38]:
# 返回陣列中不重複值
np.unique(a)

array([0, 1, 2, 3, 6, 7, 8, 9])

In [42]:
a

array([[0, 0, 8, 6, 3],
       [3, 8, 6, 2, 2],
       [9, 8, 7, 8, 1],
       [3, 3, 1, 2, 9]])

In [45]:
# 所有column的和
sum(a)

array([15, 19, 22, 18, 15])

In [46]:
# 具體某row和

sum(a[0])

17

In [48]:
# 具體某col和

sum(a[:, 0])

15

In [49]:
# 找出陣列元素最大值
a.max()

9

In [50]:
# 特定row/column中，找出陣列元素最大值

max(a[0])

8

In [51]:
sum(a[:, 0])

15

## 備註
- 關於冒號 : 的語法需要搭配python 原生list slicing觀念去理解
- 更多關於list slicing參考：
https://sites.google.com/site/ezpythoncolorcourse/indexwithslice
http://ben-do.github.io/2016/09/15/how-to-use-slice-in-python/
