# array的input/output
- 使用pickle序列化
- 為何需要做序列化這件事情?
    - 存取，供給其他function/program使用
    - pickle是python中特別的binary檔案類型，具有輕量且讀取快的優點


In [1]:
import pickle
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# f開啟名為x.pkl的檔案 以write binary模式
# 此時變數f會是準備好寫入binary的狀態，等待input內容
f = open('x.pkl', 'wb')

In [5]:
# 使用pickl.dump方法，將array x 內容 output到檔案f
# pickle檔案會被產生在同一目錄底下
pickle.dump(x, f)

In [9]:
!dir /all

 磁碟區 C 中的磁碟是 Windows
 磁碟區序號:  8C9E-DB5D

 C:\Users\Young\OneDrive\Side_Proj\data_analysis_course 的目錄

2019/10/31  下午 10:58    <DIR>          .ipynb_checkpoints
2019/10/29  下午 12:48          (35,033) array.ipynb
2019/10/31  下午 11:05             1,909 array_io.ipynb
2019/10/29  下午 11:22          (15,979) array_manipulation.ipynb
               3 個檔案          52,921 位元組
               1 個目錄  35,268,960,256 位元組可用


In [10]:
#讀入上面輸出的檔案x.pkl
# rb = read binary
f = open('x.pkl', 'rb')

In [11]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 使用numpy內的方法實現序列化

In [12]:
# 將x array存成one_array
np.save('one_array', x)

In [13]:
# 檢查同目錄下是否有one_array.npy
!dir

 磁碟區 C 中的磁碟是 Windows
 磁碟區序號:  8C9E-DB5D

 C:\Users\Young\OneDrive\Side_Proj\data_analysis_course 的目錄

2019/10/31  下午 11:11    <DIR>          .
2019/10/31  下午 11:11    <DIR>          ..
2019/10/31  下午 10:58    <DIR>          .ipynb_checkpoints
2019/10/29  下午 12:48          (35,033) array.ipynb
2019/10/31  下午 11:11             3,793 array_io.ipynb
2019/10/29  下午 11:22          (15,979) array_manipulation.ipynb
2019/10/31  下午 11:11               168 one_array.npy
2019/10/31  下午 11:08               195 x.pkl
               5 個檔案          55,168 位元組
               3 個目錄  35,266,945,024 位元組可用


In [15]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 多Array序列化

In [16]:
y = np.arange(20)

In [17]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
# 依次序列化兩個array，x取名a y取名b 存成two_array.npz
# 2個array壓縮成一個文件
np.savez('two_array.npz', a=x, b=y)

In [19]:
!dir

 磁碟區 C 中的磁碟是 Windows
 磁碟區序號:  8C9E-DB5D

 C:\Users\Young\OneDrive\Side_Proj\data_analysis_course 的目錄

2019/10/31  下午 11:19    <DIR>          .
2019/10/31  下午 11:19    <DIR>          ..
2019/10/31  下午 10:58    <DIR>          .ipynb_checkpoints
2019/10/29  下午 12:48          (35,033) array.ipynb
2019/10/31  下午 11:19             5,935 array_io.ipynb
2019/10/29  下午 11:22          (15,979) array_manipulation.ipynb
2019/10/31  下午 11:11               168 one_array.npy
2019/10/31  下午 11:19               570 two_array.npz
2019/10/31  下午 11:08               195 x.pkl
               6 個檔案          57,880 位元組
               3 個目錄  35,264,061,440 位元組可用


In [22]:
c = np.load('two_array.npz')

In [23]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])